import type { Metadata } from "next";
import "@/app/scss/globals.scss";
import Header from "@/components/Header/Header";

export const metadata: Metadata = {
  title: "News Homepage using NextJS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/ico" href="./favicon.ico" />
      </head>
      <body>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
